### ISSUE TITLE
Plugin shouldn’t do anything when not correctly initialized

### ISSUE THREAD

**Issue by PDXIII** [alvarotrigo/fullPage.js#1284]
First of all thank you for your plug in.

I would like to use FullPage.js exclusively on the index page of my blog.
Because I use CodeKit the plug in’s Javascript file is prepended to my main.js and the CSS file into my SASS file.

I built up a structure following your instruction and initialize it with `$('.fullpage').fullpage({SOME_OPTION})` and everything works fine on the index page. But on a post page which either does not have the necessary structure nor the right selector for the initialization, several unwanted things are happening.

+    My console prints: `fullPage: Error! Fullpage.js needs to be initialized with a selector. For example: $('#myContainer').fullpage();`
+    The html & body get styled `style="overflow: hidden; height: 100%;"`

This has the effect, that the page does allow scrolling. ;-(((

At the moment I don’t know what to do. When I remove the initialization everything works like expected. But when I initialize the script with an selector that does not exist on several pages, the script does unwanted things, but it just shouldn’t do anything. 

Is there any work around or do I miss something?

Best regards!

**Comment by alvarotrigo** [comment]
> The html & body get styled style="overflow: hidden; height: 100%;"

That shouldn't be happening if you use the latest version of fullpage.js (2.6.5)

The rest can easily be solved with:

```javascript
 if( $('.fullpage').lenght ){
    $('.fullpage').fullpage({SOME_OPTION})
 }
```

But I'll look into this last issue anyway. Thanks for reporting it.

**Comment by PDXIII** [comment]
Wow! You are fast! Thumbs up!!!

I updated your plug in via bower and changed the initialization according to your example, but the post did not scroll! 

Then I realized, that the SCSS file `jquery.fullPage.scss` had still version 2.6.0.
The CSS file had the right version, so I duplicated the CSS file and changed the suffix. Now everything is working fine and once again the universe is in perfect balance! 

Thank you!

**Comment by alvarotrigo** [comment]
> Plugin shouldn’t do anything when not correctly initialized

Not quite sure about that. 
Many people will only realise that something went wrong if the message is shown. 
Here are some examples:
- http://stackoverflow.com/questions/30742844/rails-and-fullpage-js-not-loading-correctly
- https://github.com/alvarotrigo/fullPage.js/issues/604
- http://stackoverflow.com/questions/28194672/fullpage-js-with-angular-js

Silently ignoring it wouldn't help in those cases.

Also, showing an error when trying to initialize a plugin with a selector that doesn't exist is usually a case of other log errors in many other plugins.

**Comment by PDXIII** [comment]
I see your point. But have still another opinion. 

I wasn't aware about the convention to put the initialization into a condition. It works know for me, so I am fine with that. 

But it still doesn't feel right. Especially when you have several plugins in your project and you first have to test if the right selector exists before you initialize the plugin.

But I am not a full time developer! So, don't mind!

**Comment by djowett** [comment]
I'm with @PDXIII on not raising an error if a selector doesn't exist on the page.  That means I don't have to vary JS page by page, which works well with the Plone CMS I'm using.

**Comment by alvarotrigo** [comment]
Solved in 2.6.7.
