### ISSUE TITLE
Cannot destroy fullpage when scrolloverflow = true

### ISSUE THREAD

**Issue by Arassas1** [alvarotrigo/fullPage.js#3117]
Destroy('all') gives error when
i) scrollOverflow = true
ii) Content of slides is bigger than height of page (i.e. when scroll is created for slide)

The error given is:
"Uncaught TypeError: Cannot read property 'destroy' of null"

Here's the jsfiddle:
https://jsfiddle.net/Arassas87/fkkf3875/43/

Note that this issue does not happen if the content of the slide fits to the page. So as a workaround, it is possible to hide/shrink the slide content, run reBuild(), and then run Destroy('all').

**Comment by alvarotrigo** [comment]
Related with the open issue https://github.com/alvarotrigo/fullPage.js/issues/3095
That was fixed in the dev branch as seen on the comments.

Use the unminified version of the scrolloverflow file from the dev branch.
See your updated fiddle working as expected:
https://jsfiddle.net/fkkf3875/48/

**Comment by Arassas1** [comment]
Thanks for the quick response. 

I was actually already using that unminified version as had come across the "getPaddings is not defined" error. It did resolve this. However the error I'm now getting is:
"Uncaught TypeError: Cannot read property 'destroy' of null"

Even in the updated jsfiddle I am still seeing this. On inspecting the HTML I can also see that not all the fullpage modifications have been destroyed.

**Comment by alvarotrigo** [comment]
True! Thanks for reporting it!! 
I'll take a look at it these days!

**Comment by alvarotrigo** [comment]
Fixed on scrollOverflow.js 0.0.8

**Comment by alvarotrigo** [comment]
Solved in the new fullPage.js release 2.9.7!
