### ISSUE TITLE
normalScrollElement bug after clicking on the element

### ISSUE THREAD

**Issue by aleksandarDeversity** [alvarotrigo/fullPage.js#3808]
Hi,

I have a problem with the normalScrollElement.

Everything works fine until you click for the first time on the element. It brakes the intended feature, and swiping over it moves to another section instead of scrolling inside an element. After you return back to the section it works again and clicking after it doesn't seem to brake it again.

You can reproduce this bug on your demo page - https://codepen.io/alvarotrigo/pen/RmVazM
Try it on phone or Chrome Inspector.
I can't reproduce this on PC, scrolling with mouse scroll works as intended after you click on the element.

**Comment by alvarotrigo** [comment]
Fixed now on dev!

**Comment by alvarotrigo** [comment]
Fixed on 3.0.8!

**Comment by aleksandarDeversity** [comment]
@alvarotrigo Awesome, thanks. Any ETA when the react-fullpage will switch to 3.0.8. since I am using it?

**Comment by alvarotrigo** [comment]
Today :)

Just give me some minutes.

**Comment by alvarotrigo** [comment]
@aleksandarDeversity 0.1.17 released!

**Comment by aleksandarDeversity** [comment]
Updated and tested it, but the bug still persists :(
I have tried it with `scrollOveflow` both `true` and `false`, but still the same behaviour as before.

0.1.17 and 3.0.8

**Comment by aleksandarDeversity** [comment]
@alvarotrigo Any update on this?

**Comment by alvarotrigo** [comment]
@aleksandarDeversity I can't see any issue in [this codepen](https://codepen.io/alvarotrigo/pen/RmVazM) on iPhone. 

Can you please detail the steps to reproduce your issue?
Include browser and device details please.

**Comment by aleksandarDeversity** [comment]
I am testing on Windows 10 laptop in chrome (inspector, set to any device with touch - phone, tablet).
Also on my android phone (OnePlus 7 Pro) in chrome too.

Testing on your codepen and also on my project before and after this new update. Same thing happens.

Swiping up or downs works normally (the normalScrollElement is scrolling) untill you do a single touch (click) on the said element (not swipe). After that swiping up or down on it results in fullpage scroll up or down. If you return back to the page with the element and try swiping again it will work normally. If you try touching it again, it also works as intended, but sometimes it bugs again.
In some really rare ocassions it will not bug, and I am not sure what is causing this.

**Comment by aleksandarDeversity** [comment]
@alvarotrigo 
I have tried it on a friends iphone in chrome right now, and it all works well as you said.

Chrome engine is different on apple devices, so I guess that is why.

**Comment by alvarotrigo** [comment]
> I am testing on Windows 10 laptop in chrome (inspector, set to any device with touch - phone, tablet).

I'm not worried about results from a simulator, those might not work as expected because they are not the real thing :)

> Chrome engine is different on apple devices, so I guess that is why.

I've tried reproducing the issue using https://browserstack.com using real Android devices (Samsung 10) and Chrome and I was not able to reproduce the issue.

Could you try in there and let me know if you manage to?

I would also make sure your phone is not catching the old version of the fullpage.js or the scrolloverflow.js file.

**Comment by a-sheriff** [comment]
Not sure if this is same issue but normalScrollElement works great on computer when using mouse and works on phone too, as far as I can tell. When using computer (surface pro) and using touch to scroll, the direction gets inverted. Not sure if this exists on other touch devices.

Using this example: https://codepen.io/alvarotrigo/pen/RmVazM ; I first drag the scrollable-content div down or up (dragging down tends to produce this more than dragging up, it would seem). Then on my first dragging of the section div the direction becomes inverted. Then I drag again and it returns to normal. And if I drag again inside the scrollable-content div  it inverts the direction once again.

**Comment by alvarotrigo** [comment]
@a-sheriff please create a new issue if you think this is a bug in fullPage.js.
And if you can provide a video that'd be great. 

But in any case,  fullPage.js doesn't control the scroll direction of the scrollable element at all. 
That's totally depending on the browser and OS.
So if the issue is there, it is probably a browser or OS issue.
