### ISSUE TITLE
Responsive slides kill all my lightbox scripts

### ISSUE THREAD

**Issue by achleitner** [alvarotrigo/fullPage.js#3819]
### Description

Whenever I resize and responsive slides kick in all my lightbox scripts are killed and  cant open them anymore. I tried many different plugins and scripts but they all stop working after resizing.
Also this https://codecanyon.net/item/jquery-paypal-html-shop/12060399 stops working too. Havent found a way to reinitialize it either. 

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. use sth like https://github.com/francoischalifour/medium-zoom
2. resize to resposnive size
3. lightboxes stop working

### Versions 
chrome, win10, all the newest fullpage js

**Comment by alvarotrigo** [comment]
You are probably not using delegation for your events / plugins.
Bear in mind that when fullapge.js converts horizontal slides into vertical sections or the other way around, the content might change in the DOM and therefore you need to bind those events or initialise those scripts again.

You can use the callback `afterResponsive` to do so.

For example:

```js
new fullpage('#fullpage', {
       afterResponsive: function(isResponsive){
             $('.demo').click(doClick);
             new exampleOfScript('#demo');
      }
});
```

**Comment by alvarotrigo** [comment]
Thinking about it twice, I'll take a look at the issue! 
I believe the solution applied in [this case](https://github.com/alvarotrigo/fullPage.js/pull/3436) can also be applied here.

**Comment by achleitner** [comment]
> You are probably not using delegation for your events / plugins.
> Bear in mind that when fullapge.js converts horizontal slides into vertical sections or the other way around, the content might change in the DOM and therefore you need to bind those events or initialise those scripts again.
> 
> You can use the callback `afterResponsive` to do so.
> 
> For example:
> 
> ```js
> new fullpage('#fullpage', {
>        afterResponsive: function(isResponsive){
>              $('.demo').click(doClick);
>              new exampleOfScript('#demo');
>       }
> });
> ```

Thanks, for the reply. I am no JS expert, but I have tried reinitializing and sometimes it worked and sometimes not. I am not experienced enough to be able to debug this. With all those scope issues.

For example I use: 

`const zoom = mediumZoom('[data-zoomable]', {
  margin: 0,
  background: '#fff',
  scrollOffset: 0
});`

Then I put: 

`mediumZoom('[data-zoomable]', {
  margin: 0,
  background: '#fff',
  scrollOffset: 0
});` or the whole 

`const zoom = mediumZoom('[data-zoomable]', {
  margin: 0,
  background: '#fff',
  scrollOffset: 0
});`

inside the  afterResponsive but it doesnt work or sometimes i get two at the same time

same with the `  $('body').ctshop({
        currency: '€',
             paypal: {
            currency_code: 'EUR',
            business: "asfasfasf"
        },
		small_cart_options: {
                
            },
			
			'before_checkout': function() {
				alert('Please indicate, that you have read and agree to the Terms and Conditions and Privacy Policy'); 
				
			},
        'after_add_to_cart': function() {
			
			$("i.fa-shopping-cart").animate({'opacity':'0','margin-bottom':'20px'},200,"linear",function(){
  $(this).animate({'opacity':'1','margin-bottom':'0px'},200);
});

            /*$('.ct-cart').css('margin-bottom', '0');*/

        }
    })`

I just put the whole thing in the after responsive but it wont work.
So no idea whats happening but it is soomething strange.

**Comment by alvarotrigo** [comment]
Try wrapping them in a setTimeout function:

```js
new fullpage('#fullpage', {
       afterResponsive: function(isResponsive){
            setTimeout(function(){
                 $('.demo').click(doClick);
                 new exampleOfScript('#demo');
          }, 600);
      }
});
```

Or refactoring a bit:

```js
new fullpage('#fullpage', {
       afterResponsive: function(isResponsive){
            setTimeout(initPlugins, 600);
      }
});


function initPlugins(){
       $('.demo').click(doClick);
        new exampleOfScript('#demo');
}
```

**Comment by achleitner** [comment]
Sweet. Thanks it works for the lightbox but still no luck with the jquery shopping cart. Kinda weird.

**Comment by achleitner** [comment]
Funny thing is when i remove the shop initialization from the domready and only initialize in the initplugins it works for the responsive mode. So seems like there is a problem when doing it a second time.

**Comment by achleitner** [comment]
Wait a second it gets weirder. It seems likonly part of the shopping cart functionality is broken. The add to cart functionality.

**Comment by achleitner** [comment]
So I'm closing in on the issue

r.on("click touchend", function(r) {

i tried to replac it with

$('body').on('click touchend', r, function (r){	

But now it always adds all the articles of the website to the cart.

Any idea how to make r.on("click touchend", function(r) { so it will check for changed elements?

**Comment by achleitner** [comment]
I found a solution:

   $(document).on('click touchend', r, function (r){	
				
				 r.stopImmediatePropagation();

**Comment by achleitner** [comment]
It's all working now! Thanks!

**Comment by achleitner** [comment]
Well i spoke too soon. It doesnt work. Would be nice to get a fix for this somehow.

**Comment by achleitner** [comment]
$(document).on('click touchend', ".ct-product-button", function (r){	
r.stopImmediatePropagation(),
r.preventDefault(),  

Now this is working

**Comment by achleitner** [comment]
Well turns out now it is adding the same product to the cart all the time.

So no luck fixing this on my own.

Would appreciate if this could somehow be fixed. 

Thanks

**Comment by achleitner** [comment]
You have any idea how I would be able to reinitialize the 

 r.on("click touchend", function(r) {
                    r.preventDefault(),
e.settings.before_add_to_cart &&


event?

 t.extend(i.prototype, {
        init: function() {
            var e = this;
            if ("true" === e.settings.display_small_cart) {
                if ("true" === e.settings.currency_after_number) var s = "0" + e.settings.currency;
                else s = e.settings.currency + "0";
                "true" === e.settings.display_total_value ? e.small_cart.append('<i class="fa fa-fw fa-shopping-cart"></i><span class="' + e.settings.small_cart + '-name">' + e.settings.small_cart_options.display_name + '&nbsp;</span><span class="' + e.settings.small_cart + '-quantity">0</span><span class="' + e.settings.small_cart + '-items">&nbsp;' + e.settings.small_cart_options.items_name + ' - </span><span class="' + e.settings.small_cart + '-price">' + s + '</span><div class="' + e.settings.cart + '-content" data-mcs-theme="' + e.settings.small_cart_options.scroll_style + '" style="display: none;  position: absolute; cursor: auto"> <div class="' + this.settings.cart + '"></div> </div>').css("cursor", "pointer") : e.small_cart.append('<i class="fa fa-fw fa-shopping-cart"></i><span class="' + e.settings.small_cart + '-name">' + e.settings.small_cart_options.display_name + '&nbsp;</span><span class="' + e.settings.small_cart + '-quantity">0</span><span class="' + e.settings.small_cart + '-items">&nbsp;' + e.settings.small_cart_options.items_name + '</span><div class="' + e.settings.cart + '-content" data-mcs-theme="' + e.settings.small_cart_options.scroll_style + '" style="display: none;  position: absolute; cursor: auto"> <div class="' + this.settings.cart + '"></div> </div>').css("cursor", "pointer"), "true" === e.settings.small_cart_options.wishlist && e.small_cart.find("." + e.settings.cart + "-content").append('<div class="' + e.settings.wishlist + '"></div>');
                var i = "." + e.settings.cart + "-content";
                "true" === e.settings.small_cart_options.scroll && t(i).addClass("mCustomScrollbar").css("max-height", e.settings.small_cart_options.scroll_height + "px"), e.small_cart.on("mouseenter", function() {
                    t(i).show()
                }).on("mouseleave", function() {
                    t(i).hide()
                })
            }
            if ("true" === e.settings.display_small_cart && (this.cart = this.element.find("." + this.settings.small_cart + " ." + this.settings.cart)), e.cart = e.cart.append("<ol/>").find("ol"), "true" === e.settings.display_small_cart && "true" === e.settings.small_cart_options.wishlist && (this.wishlist = this.element.find("." + this.settings.small_cart + " ." + this.settings.wishlist)), e.settings.wishlist && (e.wishlist = e.wishlist.append("<ol/>").find("ol"), window.sessionStorage["ct-shopping-wishlist"])) {
                var n = e.wishlist.find("li").length;
                e.create_storage_wish(), e.remove_item(n, !0)
            }
            if (e.permanent_total(), e.permanent_cart_buttons(), window.sessionStorage["ct-shopping-cart"] && e.cart.length) {
                e.create_storage_cart();
                var a = e.cart.find("li"),
                    o = a.find("." + e.settings.cart + "-input"),
                    r = a.length;
                "false" === e.settings.permanent_cart_buttons && e.add_cart_buttons(), "true" === e.settings.display_total_value && "false" === e.settings.permanent_total_value && e.append_total(), "true" === e.settings.promo_codes && e.add_promo_code(), e.calculate_total_value(), e.quantity_change(o), e.remove_item(r)
            }
            e.settings.init && e.settings.init(), e.cart_empty(), e.product.each(function(s) {
                var i = t(this),
                    n = e.absolute_url() + i.find("." + e.settings.product_image).attr("src"),
                    a = i.find("." + e.settings.product_title),
                    o = i.find("." + e.settings.product_price),
                    r = i.find("." + e.settings.product_button),
                    l = a.text(),
                    c = o.text().replace(",", "").replace(/[^\d.]/g, "");
                e.settings.wishlist && i.find("." + e.settings.product_wishlist).on("click touchend", function(t) {
                    t.preventDefault(), e.settings.before_add_to_wishlist && e.settings.before_add_to_wishlist(), l = e.check_if_title(a, l), c = e.check_if_price(o, c);
                    var r, p = i.attr("data-id", l.replace(/ /g, "").replace(/\r\n|\r|\n/g, "").replace(/[^a-zA-Z 0-9]+/g, "") + c.replace(/\r\n|\r|\n/g, "").replace(/[^a-zA-Z 0-9]+/g, "") + "_" + (s + 1)).attr("data-id"),
                        h = e.wishlist.find("li"),
                        u = e.wishlist.find("[data-id=" + p + "]").attr("data-id"),
                        d = e.cart.find("[data-id=" + p + "]");
                    return (d.length || 0 === h.length || u === p) && (0 !== h.length || d.length) || e.add_to_wishlist(l, c, p, n), r = (h = e.wishlist.find("li")).length, e.remove_item(r, !0), e.settings.after_add_to_wishlist && e.settings.after_add_to_wishlist(), !1
                });
            r.on("click touchend", function(r) {
                    r.preventDefault(),
e.settings.before_add_to_cart &&

**Comment by achleitner** [comment]
is there maybe a way to reload the page when the responsive event fires? only once without being stuck in a reload loop

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 3.0.9! 👍

**Comment by jmplos** [comment]
hi @alvarotrigo , I bought some months ago fullpage for elementor and i think i might have this issue, yet it is far over my current level.

Lightbox fades in and inmediately out when fullpage enabled. I'm getting no logs in console. I've disabled all my custom callback functions and css, still happening.

Now, if you click an image right after scrolling, it works! I'm out of ideas

**Comment by alvarotrigo** [comment]
For Elementor issues please use the [contact form](https://alvarotrigo.com/#contact).

**Comment by alvarotrigo** [comment]
@jmplos but notice that if you purchased it more than a month ago you might have to upgrade your plan to increase your support time.
