### ISSUE TITLE
Set height of section

### ISSUE THREAD

**Issue by maxbeech** [alvarotrigo/fullPage.js#628]
Hi there!

First, great plugin, many thanks indeed!
Second, this may sound very noobish, but can't figure how to set a section to have a height of less than 100%, I have tried setting it in the css using .section and #section1 (eg. height: 80%;), but this has no effect...

Many thanks.

Max

**Comment by monolux** [comment]
@alvarotrigo The fiddle is great for people that like to have other use cases of fullPage. Thank you Álvaro.

**Comment by alvarotrigo** [comment]
@monolux the problem with setting the height of the section was solved time ago by the provided class `fp-auto-height` as detailed [in the documentation](https://github.com/alvarotrigo/fullPage.js#creating-smaller-sections).

**Comment by monolux** [comment]
@alvarotrigo Thank you! If you are interested why I find this good here is the use case I am trying to get working and I think I am nearly finished.

I have a fixed top div that is the navigation, a navbar. This navbar uses flowType to have the nabar menu links change font size according to viewport width and height. Naturally each of the menu items is a div (with the menu link inside) and these divs change height according to the font size of the menu link. This leads to the entire navbar changing height dynamically.

[Here](http://stackoverflow.com/questions/35584337/fullpagejs-fixed-header-z-index-hides-sections-content) I have found a similar question but see now that just dynamically adding a padding-top value to the `fp-tableCell` class like outlined does not always work.

Instead I think I will either try to add this dynamically changing padding-top value from the changing navbar's height to each of the sections so that the fixed navbar does not hide part of the section content or I will simply add a buffer/placeholder div with the height of the current navbar height to the top of each section, again to not have section content hidden by the navbar.

This I guess would have to be done with `afterRender` and `afterResize`, while having `scrollOverflow:true`, as, especially on PDAs things get wonky. Testing a few things and might make a fiddle with the solution.

Unfortunately `fixedElements:'#navbar'` removes the navbar from the entire site, so I am not exactly sure how to use or work with that just jet, but I am digging.

Related: slimscrollJS has quite static/slow scrolling on PDAs I discovered, will have to see how to tune slimsscrollJS settings to resemble the scrolling more like on a native device.

**Comment by monolux** [comment]
I managed with the placeholder approach without any extra `afterRender` and|or `afterResize` methods used by adding the placeholde dynamically to each section with the height of the navbar that itself also has changing height. The padding-top way from SE does not work. Will try and get a fiddle going.

**Comment by monolux** [comment]
[Here](https://jsfiddle.net/gvsasrnw/) is the fiddle with fixed navigation that has a dynamic height depending on viewport width and height.
Still not sure what exactly the `fixedElements` option does but the way I managed with the placeholder it works just fine.
Having the `fp-tableCell` rule set to `middle` had to be changed to `top`. For practical reasons I wanted to have the content inside sections to start at the top of the section and not in the middle.
